(function () {
  'use strict';
  if (window.EyeX && window.EyeX.__widgetLoaded) return;
  var script=document.currentScript;
  var src=script&&script.src?new URL(script.src,window.location.href):new URL(window.location.href);
  var apiBase=(script&&script.dataset.eyexApi?script.dataset.eyexApi:src.origin).replace(/\/$/,'');
  var keys=['background','surface','text','primary','secondary','error','success'];
  var labels={deuteranopia:'Rojo-verde',tritanopia:'Azul-amarillo',achromatopsia:'Todo en grises'};
  function systemMode(){return window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}
  function setPalette(data){keys.forEach(function(key){document.documentElement.style.setProperty('--eyex-'+key,data.palette[key]);});document.documentElement.dataset.eyexTheme=data.type;document.body.style.backgroundColor='var(--eyex-background)';document.body.style.color='var(--eyex-text)';}
  async function apply(type,options){options=options||{};var q=new URLSearchParams({severity:options.severity||'moderate',mode:options.mode||systemMode(),high_contrast:String(Boolean(options.highContrast))});var response=await fetch(apiBase+'/api/v1/theme/'+encodeURIComponent(type)+'?'+q,{headers:{Accept:'application/json'}});var data=await response.json();if(!response.ok)throw new Error(data.message||data.error||'EyeX request failed');setPalette(data);localStorage.setItem('eyex-widget-theme',data.type);return data;}
  function injectStyles(){var style=document.createElement('style');style.id='eyex-widget-style';style.textContent='body{transition:background-color .15s,color .15s}a{color:var(--eyex-primary)!important}#eyex-widget{position:fixed;right:18px;bottom:18px;z-index:2147483647;font-family:Arial,sans-serif}#eyex-toggle{width:50px;height:50px;border:0;border-radius:25px;background:#222831;color:#fff;box-shadow:0 2px 9px #0005;cursor:pointer;font-weight:700}#eyex-panel{display:none;position:absolute;right:0;bottom:60px;width:245px;padding:12px;background:#fff;color:#20252B;border:1px solid #8b949e;box-shadow:0 4px 18px #0004}#eyex-panel.open{display:grid;gap:8px}#eyex-panel button[data-type]{height:34px;text-align:left;background:#fff;color:#20252B;border:1px solid #9aa2aa;cursor:pointer}#eyex-panel small{color:#606a74}';document.head.appendChild(style);}
  function makeWidget(){var host=document.createElement('div');host.id='eyex-widget';var panel=document.createElement('div');panel.id='eyex-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Opciones EyeX');var title=document.createElement('strong');title.textContent='Selección manual';panel.appendChild(title);Object.keys(labels).forEach(function(type){var button=document.createElement('button');button.type='button';button.dataset.type=type;button.textContent=labels[type];button.addEventListener('click',function(){apply(type,{highContrast:type==='achromatopsia'}).then(function(){panel.classList.remove('open');});});panel.appendChild(button);});var note=document.createElement('small');note.textContent='El modo claro u oscuro se detecta automáticamente.';panel.appendChild(note);var toggle=document.createElement('button');toggle.id='eyex-toggle';toggle.type='button';toggle.textContent='EyeX';toggle.setAttribute('aria-label','Abrir EyeX');toggle.addEventListener('click',function(){panel.classList.toggle('open');});host.appendChild(panel);host.appendChild(toggle);document.body.appendChild(host);}
  function init(){injectStyles();makeWidget();var saved=localStorage.getItem('eyex-widget-theme');if(saved&&labels[saved])apply(saved,{highContrast:saved==='achromatopsia'}).catch(function(error){console.warn('[EyeX]',error);});}
  window.EyeX={__widgetLoaded:true,apply:apply,apiBase:apiBase};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}());
